
#pragma once
#include <iostream>
#include <ctime>
#include <cmath>
#include <functional>
#include <cstdio>
#include <array>
#include <iterator>
#include <vector>
#include <algorithm>
#include <limits>
#include <cstdint>
#include <fstream>
#include <unistd.h>
#include <cstdlib>
#include <sstream>
#include <string>
#include <map>
#include <time.h>
#include <cstring>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/select.h>
#include <dirent.h>
#include <random>
#include <iomanip>
#include <switch.h>
#include <switch/arm/atomics.h>
using namespace std;